<?php

namespace App\form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @method getChoices()
 */
class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub//}


         {
               $builder
                   ->add('title')
                   ->add('description')
                   ->add('surface')
                   ->add('rooms')
                   ->add('bedrooms')
                   ->add('floor')
                   ->add('color', ChoiceType::class, [
                       'choices' => $this->getChoices()
                   ])
                   ->add('heat', ChoiceType::class, [
                       'choices' => $this->getChoices()
                   ])
                   ->add('city')
                   ->add('address')
                   ->add('postal_code')
                   ->add('sold')
               ;}


        public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }


         }
}

